### ISSUE TITLE
Incorrect sequence with two vowels on one consonant

### ISSUE THREAD

**Issue by charlesLoder** [charlesLoder/hebrew-transliteration#16]
See charlesLoder/hebrewTransliteration#1

> In cases of more then one vowel on a letter the sequence messes it up
eg: יְרְוּשָׁלִָֽם
is sequeced as יְרְוּשָׁלִָֽם
which is a mistake.
this is the two words in hex
`&#x05D9;&#x05B0;&#x05E8;&#x05B0;&#x05D5;&#x05BC;&#x05E9;&#x05C1;&#x05B8;&#x05DC;&#x05B8;&#x05BD;&#x05B4;&#x05DD;`
`&#x05D9;&#x05B0;&#x05E8;&#x05B0;&#x05D5;&#x05BC;&#x05E9;&#x05C1;&#x05B8;&#x05DC;&#x05B4;&#x05B8;&#x05BD;&#x05DD;`

**Comment by charlesLoder** [comment]
@benemanuel so this issue actually resides in my havarotjs package which does the syllabification. See the latest issue [here](https://github.com/charlesLoder/havarot/issues/26).

One question, where do you find the spelling "יְרְוּשָׁלִָֽם"? The shewa under the resh is unique. I don't think I've found any instances like that in the Tanakh. Is this a mishanic/talmudic spelling?

**Comment by benemanuel** [comment]
When opening the case it seems that I misspelled יְרֽוּשָׁלִָֽם. I also do not know of a case which a SHEWA is under the RESH.

**Comment by charlesLoder** [comment]
Fixed in [havarotjs](https://github.com/charlesLoder/havarot/pull/27)
