### ISSUE TITLE
Add callback to additional features

### ISSUE THREAD

**Issue by charlesLoder** [charlesLoder/hebrew-transliteration#38]
Additional features option, should be able to take a `string` or a callback function

```js
ADDITIONAL_FEATURES: [{
    FEATURE: "word",
    HEBREW: "הָאָֽרֶץ",
    TRANSLITERATION: (word) => { /** do something here* / }
  }]
```
The callback type definition would have to change depending on the `FEATURE` selected.

Additionally, the `HEBREW` property already gets converted to a regex, so a regex should be allowed too

**Comment by johnlockejrr** [comment]
Good idea! This should bypass the exceptional cases like שְׁתַּיִם (that was exceptionally consonantal cluster in Proto Semitic also). Is this implemmented globally or by transcription "tradition" (SBL, Brill etc.)?
