### ISSUE TITLE
divine name when vowels is read Elohim shows identical to YHWH

### ISSUE THREAD

**Issue by benemanuel** [charlesLoder/hebrew-transliteration#40]
were it is written אדני יהוה. shouldn't be yhvh yhvh.

**Comment by benemanuel** [comment]
list of such verses.
Gen15:2,Gen15:8,Deut3:24,Deut9:26,Josh7:7,Judg6:22,Judg16:28,2Sam7:18,2Sam7:19,2Sam7:19,2Sam7:20,2Sam7:28,2Sam7:29,1Kings2:26,1Kings8:53,Ps69:7,Ps71:5,Ps71:16,Isa3:15,Isa7:7,Isa10:23,Isa10:24,Isa22:12,Isa22:14,Isa22:15,Isa25:8,Isa28:16,Isa28:22,Isa30:15,Isa40:10,Isa48:16,Isa49:22,Isa50:4,Isa50:5,Isa50:9,Isa52:4,Isa56:8,Isa61:1,Isa61:11,Isa65:13,Isa65:15,Jer1:6,Jer2:19,Jer2:22,Jer4:10,Jer7:20,Jer14:13,Jer32:17,Jer32:25,Jer44:26,Jer49:5,Jer50:31,Ezek2:4,Ezek3:11,Ezek3:27,Ezek4:14,Ezek5:5,Ezek5:7,Ezek5:8,Ezek5:11,Ezek6:3,Ezek6:3,Ezek6:11,Ezek7:2,Ezek7:5,Ezek8:1,Ezek9:8,Ezek11:7,Ezek11:8,Ezek11:13,Ezek11:16,Ezek11:17,Ezek11:21,Ezek12:10,Ezek12:19,Ezek12:23,Ezek12:25,Ezek12:28,Ezek12:28,Ezek13:3,Ezek13:8,Ezek13:8,Ezek13:9,Ezek13:13,Ezek13:16,Ezek13:18,Ezek13:20,Ezek14:4,Ezek14:6,Ezek14:11,Ezek14:14,Ezek14:16,Ezek14:18,Ezek14:20,Ezek14:21,Ezek14:23,Ezek15:6,Ezek15:8,Ezek16:3,Ezek16:8,Ezek16:14,Ezek16:19,Ezek16:23,Ezek16:30,Ezek16:36,Ezek16:43,Ezek16:48,Ezek16:59,Ezek16:63,Ezek17:3,Ezek17:9,Ezek17:16,Ezek17:19,Ezek17:22,Ezek18:3,Ezek18:9,Ezek18:23,Ezek18:30,Ezek18:32,Ezek20:3,Ezek20:3,Ezek20:5,Ezek20:27,Ezek20:30,Ezek20:31,Ezek20:33,Ezek20:36,Ezek20:39,Ezek20:40,Ezek20:44,Ezek21:3,Ezek21:5,Ezek21:12,Ezek21:18,Ezek21:29,Ezek21:31,Ezek21:33,Ezek22:3,Ezek22:12,Ezek22:19,Ezek22:28,Ezek22:31,Ezek23:22,Ezek23:28,Ezek23:32,Ezek23:34,Ezek23:35,Ezek23:46,Ezek23:49,Ezek24:3,Ezek24:6,Ezek24:9,Ezek24:14,Ezek24:21,Ezek24:24,Ezek25:3,Ezek25:3,Ezek25:6,Ezek25:8,Ezek25:12,Ezek25:13,Ezek25:14,Ezek25:15,Ezek25:16,Ezek26:3,Ezek26:5,Ezek26:7,Ezek26:14,Ezek26:15,Ezek26:19,Ezek26:21,Ezek27:3,Ezek28:2,Ezek28:6,Ezek28:10,Ezek28:12,Ezek28:22,Ezek28:24,Ezek28:25,Ezek29:3,Ezek29:8,Ezek29:13,Ezek29:16,Ezek29:19,Ezek29:20,Ezek30:2,Ezek30:6,Ezek30:10,Ezek30:13,Ezek30:22,Ezek31:10,Ezek31:15,Ezek31:18,Ezek32:3,Ezek32:8,Ezek32:11,Ezek32:14,Ezek32:16,Ezek32:31,Ezek32:32,Ezek33:11,Ezek33:25,Ezek33:27,Ezek34:2,Ezek34:8,Ezek34:10,Ezek34:11,Ezek34:15,Ezek34:17,Ezek34:20,Ezek34:30,Ezek34:31,Ezek35:3,Ezek35:6,Ezek35:11,Ezek35:14,Ezek36:2,Ezek36:3,Ezek36:4,Ezek36:4,Ezek36:5,Ezek36:6,Ezek36:7,Ezek36:13,Ezek36:14,Ezek36:15,Ezek36:22,Ezek36:23,Ezek36:32,Ezek36:33,Ezek36:37,Ezek37:3,Ezek37:5,Ezek37:9,Ezek37:12,Ezek37:19,Ezek37:21,Ezek38:3,Ezek38:10,Ezek38:14,Ezek38:17,Ezek38:18,Ezek38:21,Ezek39:1,Ezek39:5,Ezek39:8,Ezek39:10,Ezek39:13,Ezek39:17,Ezek39:20,Ezek39:25,Ezek39:29,Ezek43:18,Ezek43:19,Ezek43:27,Ezek44:6,Ezek44:9,Ezek44:12,Ezek44:15,Ezek44:27,Ezek45:9,Ezek45:9,Ezek45:15,Ezek45:18,Ezek46:1,Ezek46:16,Ezek47:13,Ezek47:23,Ezek48:29,Amos1:8,Amos3:7,Amos3:8,Amos3:11,Amos3:13,Amos4:2,Amos4:5,Amos5:3,Amos6:8,Amos7:1,Amos7:2,Amos7:4,Amos7:4,Amos7:5,Amos7:6,Amos8:1,Amos8:3,Amos8:9,Amos8:11,Amos9:8,Obad1:1,Mic1:2,Zeph1:7

**Comment by charlesLoder** [comment]
Not sure if I totally understand, so let me reiterate to see if I have it right.

It currently produces:

```js
heb.transliterate("אֲדֹנָ֤י יֱהֹוִה֙");
// ʾădōnāy yhwh 👎
```
but rather should be like this:

```js
heb.transliterate("אֲדֹנָ֤י יֱהֹוִה֙");
// ʾădōnāy ʾĕlōhîm 👍
```

If that's what you're saying, then I'll look at adjusting the `ADDITIONAL_FEATURES` property. Which currently produces:

```js
heb.transliterate("אֲדֹנָ֤י יֱהֹוִה֙", {
  ADDITIONAL_FEATURES: [
    {
      FEATURE: "word",
      HEBREW: "יֱהֹוִה֙",
      TRANSLITERATION: "ʾĕlōhîm"
    }
  ]
});
// ʾădōnāy yhwh  👎
```

In short, because this package is about transliteration and not transcription, what happens is what I would expect. Of course, the Divine Name is always an outlier because of its unique pointing and history of usage.

I'll leave this issue open while I consider a best way to handle this

**Comment by charlesLoder** [comment]
I recently had a new addition to my family so work on this project has been slowed.
