### ISSUE TITLE
Suggestion: DAGESH_CHAZAQ character addition

### ISSUE THREAD

**Issue by asherlporetz** [charlesLoder/hebrew-transliteration#41]
Is it possible to overload DAGESH_CHAZAQ to accept a character, like a combining circumflex for example. And it will be applied to any dagesh forte (but not lene) and to mappiq He as well. Thank you.

**Comment by asherlporetz** [comment]
Also for STRESS_MARKER, maybe add a field to specify not to add the mark if it's at the expected/default location which is the last syllable. "always": false, for the default. "always": true, for the current behavior.

**Comment by charlesLoder** [comment]
Thanks for the ideas! I recently had a new addition to my family so work on this project has been slowed.

> Is it possible to overload DAGESH_CHAZAQ to accept a character, like a combining circumflex for example. And it will be applied to any dagesh forte (but not lene) and to mappiq He as well. Thank you.

That could be done.

As an exmple:

```js
transliterate("שַׁבָּת", { DAGESH_CHAZAQ: "̂" }) ;

// šab̂āt
```

If that's not what you're suggesting, please put a sample.

---

> Also for STRESS_MARKER, maybe add a field to specify not to add the mark if it's at the expected/default location which is the last syllable. "always": false, for the default. "always": true, for the current behavior.

Is this what you're suggesting:

```js
transliterate("שַׁבָּת אֶרֶץ",  { STRESS_MARKER : {
  location:'after-vowel', 
  mark: '\u0301' 
  always: false
});

// šabbāt ʾéreṣ
```

**Comment by asherlporetz** [comment]
@charlesLoder exactly what I was trying to convey. Thank you.

**Comment by BillMeyerRSA** [comment]
That would be helpful. It might be problematic at times with combining diacritical when using e.g. sh for SHIN or tz for TSADI - two letter.

**Comment by charlesLoder** [comment]
> That would be helpful. It might be problematic at times with combining diacritical when using e.g. sh for SHIN or tz for TSADI - two letter.

That's a good point, but unfortunately unavoidable.

For the [SBL Simple schema](https://github.com/charlesLoder/hebrew-transliteration/blob/ca58a5de21bb1437fb7a49a466f1a50663464ca9/src/schemas/sblSimple.ts#L64), ensuring that a shin/tsazi with a dagesh chazaq is doubled, requires using an additional feature.

```js
  ADDITIONAL_FEATURES: [
    {
      FEATURE: "cluster",
      HEBREW: "\u{05E9}\u{05C1}\u{05BC}",
      TRANSLITERATION: "sh"
    },
    {
      FEATURE: "cluster",
      HEBREW: "\u{05E6}\u{05BC}",
      TRANSLITERATION: "ts"
    }
  ],
```
So if a user wanted to use an [acute accent](https://www.compart.com/en/unicode/U+0301) as a dagesh marker and used a digraph for shin/tsadi, it would have to look something like:

```js
  DAGESH_CHAZAQ: "\u0301"
  ADDITIONAL_FEATURES: [
    {
      FEATURE: "cluster",
      HEBREW: "\u{05E9}\u{05C1}\u{05BC}",
      TRANSLITERATION: "śh" // or whatever
    },
    {
      FEATURE: "cluster",
      HEBREW: "\u{05E6}\u{05BC}",
      TRANSLITERATION: "tś" // or whatever
    }
  ],
```

That is some duplication of work, but a schema assumes a one-to-one correspondence between Hebrew and transliteration.
