### ISSUE TITLE
Problem with Resh ḥōlem 

### ISSUE THREAD

**Issue by BillMeyerRSA** [charlesLoder/hebrew-transliteration#42]
I expected output of bêt ḥôron, but got bêt ḥôrn for בֵּית חוֹרֹן . 
![image](https://user-images.githubusercontent.com/38781014/211181169-42beb344-d89a-4c97-9a4a-e1cad9330197.png)

**Comment by BillMeyerRSA** [comment]
Correction. Seems to not bet specific to Resh. Likely due to two adjacent letters having ḥōlem.

![image](https://user-images.githubusercontent.com/38781014/211181337-061644ff-b3d9-47eb-b0cc-21582302bc81.png)

**Comment by charlesLoder** [comment]
Thanks for finding this! I recently had a new addition to my family so work on this project has been slowed.

**Comment by BillMeyerRSA** [comment]
> Thanks for finding this! I recently had a new addition to my family so work on this project has been slowed.

New boss in the home...

**Comment by BillMeyerRSA** [comment]
Additional information for likely same problem: כּ֫וֹרֶשׁ
![image](https://user-images.githubusercontent.com/38781014/211458319-78c18213-1705-4fe5-9c5b-db7618aaff51.png)

**Comment by charlesLoder** [comment]
The issue of בֵּית חוֹרֹן is closed in v0.13.0 of [havarotjs](https://github.com/charlesLoder/havarotjs/issues/85)

The issue of בֵּית חוֹרֹן is closed in v0.13.1 of [havarotjs](https://github.com/charlesLoder/havarotjs/issues/96)
