### ISSUE TITLE
Problem with בִּנְגִינ֗וֹת

### ISSUE THREAD

**Issue by BillMeyerRSA** [charlesLoder/hebrew-transliteration#44]
Problem with בִּנְגִינ֗וֹת in Teh 4:1. expected beneḡinoṯ
![image](https://user-images.githubusercontent.com/38781014/211228583-947b4719-f874-4b41-8c3a-99f1d7b53d5c.png)

**Comment by charlesLoder** [comment]
> expected beneḡinoṯ

That would indicate that the sheva is vocal, which it isn't (I believe).

"bingînôt" is the correct transliteration for the default schema
