### ISSUE TITLE
double marks

### ISSUE THREAD

**Issue by asherlporetz** [charlesLoder/hebrew-transliteration#61]
Not sure of settings but the following fail if inserted in the tests. Text from Sefaria.
produces double dagesh mark instead:
```
    ${"sin dagesh "}   | ${"הַשָּׂדֶֽה"} | ${"haśādê"}   | ${{ DAGESH_CHAZAQ: "\u0301" }}
```
produces double stress mark instead:
```
    ${"geresh"}   | ${"עֵ֝ינֶ֗יךָ"}   | ${"ʿênêˈkā"}   | ${{ STRESS_MARKER: { location: "after-syllable", mark: "ˈ" } }}
```
produces "ha" instead of "ah":
```
    ${"furtive patach, sof pasuq"}   | ${"רֽוּחַ׃"}    | ${"rûaḥ"}
``` 
does not separate maqaf:
```
    ${"psalms 2:12 maqaf"}  |  ${"נַשְּׁקוּ־בַ֡ר"}  |  ${"naššǝqû-bar"}
```

By the way is it possible to have SILENT_SHEVA and MAPPIQ settings (default to blank strings)? For example "שַׁוְעִ֗י" can become "shavi" if silent sheva is not marked, instead of "shav,i". And "הִ֛וא" occurs often enough that it would be great to have a setting for it instead of the cpu-consuming ADDITIONAL_FEATURES; right now it translates to "hiv'" instead of just "hi". Thank you for this project!

**Comment by charlesLoder** [comment]
@asherlporetz 

Just noting that I see this.

Had a baby a few months ago, and time on this project has slowed

**Comment by asherlporetz** [comment]
No rush. The library is very useful as it is. Have a great time!

**Comment by charlesLoder** [comment]
Found some free time! 

I assume these are your own tests?

I'll try to take them one-by-one

---

<br>
<br>

> produces double dagesh mark instead:

The `\u0301` character is being applied to `ś`, which already has an acute on it.

You would have to write an `ADDITIONAL_FEATURE` to fix that.

<br>
<br>

> produces double stress mark instead:

It's counting the geresh and the revia as stressed syllables.

What text is that from? That may be a bug, or my limited understanding of taamim (almost certainly the latter).

<br>
<br>

> produces "ha" instead of "ah":

Interesting, if you copy & paste from a text like [Mishneh Torah](https://www.sefaria.org/Mishneh_Torah%2C_Repentance.2.4?vhe=Torat_Emet_363&lang=bi), the _sof pasuq_  after רוּחַ is actually a colon, but in [Psalms 18:11](https://www.sefaria.org/Psalms.18.11?vhe=Tanach_with_Ta%27amei_Hamikra&lang=bi) it's an actual _sof pasuq_.

This is definitely a bug 🐞 

<br>
<br>


> does not separate maqaf:

Another bug! 🐞 


<br>
<br>

> By the way is it possible to have SILENT_SHEVA and MAPPIQ settings (default to blank strings)? 

I like this idea, but not totally sure I follow the first example.

> example "שַׁוְעִ֗י" can become "shavi" if silent sheva is not marked, instead of "shav,i". 

With the default settings, I get:

```js
console.log(heb.transliterate(`שַׁוְעִ֗י`));
// šawʿî
```
The `ʿ` character is the ayin. Is that what you mean in "shav,i"?

> And "הִ֛וא" occurs often enough that it would be great to have a setting for it instead of the cpu-consuming ADDITIONAL_FEATURES;

Yeah, the `ADDITIONAL_FEATURES` are not optimized at all. 

I'm not too sure how to check a word like this other than just a regex, which would be pretty similar to an `ADDITIONAL_FEATURE`. 

I'll have to mull over it. If you have any ideas, drop them here.

**Comment by charlesLoder** [comment]
Closes this. New issues have been created
