### ISSUE TITLE
Maqqaf after shureq is dropped

### ISSUE THREAD

**Issue by charlesLoder** [charlesLoder/hebrew-transliteration#62]
When a maqqaf is after a shureq (e.g. "נַשְּׁקוּ־בַ֡ר"), it is dropped.

```js
console.log(heb.transliterate(`נַשְּׁקוּ־בַ֡ר`));
// expected: naššǝqû-bar
// received: naššǝqûbar
```

See [original issue](https://github.com/charlesLoder/hebrew-transliteration/issues/61).

**Comment by charlesLoder** [comment]
This is caused b/c the maqqaf is part of the `Cluster`.

Should it be?

**Comment by johnlockejrr** [comment]
To be or not to be :)
In the Tiberian tradition maqqaf makes from two or three words one in
pronounciation but gramatically they remain independent words.
