### ISSUE TITLE
SHEVA in Schema

### ISSUE THREAD

**Issue by Zalexei** [charlesLoder/hebrew-transliteration#63]
I'm trying to change scheme to be able to produce IPA representation. Could you please recommend how to deal with SHEVA Diphthong: usually it should be represented as empty sound, but in some words like 'מְתוּקִים' 'נְקֻדָּה' 'צְהֻבִּים' it should act as 'e'. Haven't found the way to differentiate cases - or it's very specific?

Also what is the best way to define j sound ('ג'ון') - as additional_feature?

**Comment by Zalexei** [comment]
Sorry, wasn't attentive to details: found example with exact problem in the documentation. Do you know what can be the problem that instead of replacing by result of function it replaces it with function body code:

```const heb = require("hebrew-transliteration");
// const rules = require("hebrew-transliteration/dist/rules"); // causes error - not exported
const transliterate = heb.transliterate;

console.log(heb.transliterate("בְּרֵאשִׁ֖ית וַיַּבְדֵּל", {
    ADDITIONAL_FEATURES: [
      {
        // matches any sheva in a syllable that is NOT preceded by a vowel character
        HEBREW: "(?<![\u{05B1}-\u{05BB}\u{05C7}].*)\u{05B0}",
        FEATURE: "syllable",
        TRANSLITERATION: function (syllable: { next: any; text: string; }, _hebrew: any, schema: { [x: string]: string; }) {
          const next = syllable.next;
          // ensure type safety
          const nextVowel = next.vowelName === "SHEVA" ? "VOCAL_SHEVA" : next.vowelName;
  
          if (next && nextVowel) {
            const vowel = schema[nextVowel] || "";
            return syllable.text.replace(new RegExp("\u{05B0}", "u"), vowel);
          }
  
          return syllable.text;
        }
      }
    ]
  }));```

The output is: 
`
C:\Developer\node_test>ts-node index.ts
Start
bǝrēʾšît wayyabdēl
bfunction (syllable, _hebrew, schema) {
                const next = syllable.next;
                // ensure type safety
                const nextVowel = next.vowelName === "SHEVA" ? "VOCAL_SHEVA" : next.vowelName;
                if (next && nextVowel) {
                    const vowel = schema[nextVowel] || "";
                    return syllable.text.replace(new RegExp("\u{05B0}", "u"), vowel);
                }
                return syllable.text;
            }rēʾšît wayyabdēl
`

**Comment by johnlockejrr** [comment]
“SHEVA Diphthong”? Thre’s no such thing.

**Comment by charlesLoder** [comment]
@Zalexei could you define what you mean by "SHEVA Diphthong"? Your examples seem to indicate a vocal sheva (also called 'sheva na'), which is the [`VOCAL_SHEVA`](https://github.com/charlesLoder/hebrew-transliteration/blob/aadbfbac22a00d80d257094149375c09075a9e3c/src/schema.ts#L278) property.

---

> Also what is the best way to define j sound ('ג'ון') - as additional_feature?

Yes, the spelling conventions in modern Hebrew for 'j' and 'ch' aren't defined in the schema (this package is more focused on Biblical Hebrew), so an `ADDITIONAL_FEATURE` would have to be used

**Comment by charlesLoder** [comment]
Stale
