### ISSUE TITLE
Vocal Shewa

### ISSUE THREAD

**Issue by JacobWeinbren** [charlesLoder/hebrew-transliteration#70]
In this library, the Shewa is substituted for a ǝ - when in some (most) cases it should be silent. 

For example, "בְּרוּכָה הַבָּאָה" produces "bǝrûkâ habbāʾâ". when it should be "brûkâ habbāʾâ"

Is there any clear way to solve this? 

Thank you for making this library.

**Comment by johnlockejrr** [comment]
Who says shewa is silent in that case? Maybe in Ivrit but not in Biblical
Hebrew.

**Comment by charlesLoder** [comment]
@JacobWeinbren 

I'm glad you're finding the library useful!

As @johnlockejrr noted in Biblical Hebrew the sheva in בְּרוּכָה is most certainly vocal.

In Modern Hebrew, however, the sheva would be silent, so the bet and resh would be blended together like in English.

For your case, you could set the VOCAL_SHEVA to an empty string:

```js
transliterate("בְּרוּכָה", { VOCAL_SHEVA: "" })
// brûkâ
```

This can be done on the website's interface as well.

This is probably you're best bet.

---

Though that solves your immediate use case, it will still give some incorrect results with a few words. For a word like לְבָנִים, even though it has an initial sheva like בְּרוּכָה, in Modern Hebrew, unlike בְּרוּכָה, the sheva is pronounced — _lǝvanim_.

If you're curious, there's more [here](https://github.com/charlesLoder/havarotjs/issues/4).

Hope that helps

**Comment by JacobWeinbren** [comment]
@charlesLoder 

Is there any way to address the other cases for modern Ivrit? How would I use Syllable.medial to achieve this?

https://judaism.stackexchange.com/questions/92599/what-are-the-rules-for-shva-na

> 1. first letter of a word.
> 2. second of two shvas under consecutive letters.
> 3. after a tenua gedolah(long vowel), where the long vowel has no primary stress.(also some other cases, and can even be after a short vowel where the short vowel is "lengthened"/treated as a long vowel!)
> 4. under a dagesh
> 5. if a shva appears under the first of two consecutive identical letters (e.g., the first lamed of halleluyah)

This is the closest I could find to a comprehensive ruleset for all the cases where sheva is pronounced. 

Thank you!

**Comment by JacobWeinbren** [comment]
@charlesLoder I am not confident enough in Hebrew to write a callback that would apply to most of the rules and exceptions of modern Ivrit to the vocal Shewa. There are so many potential exceptions. If I understand you correctly, this seems a significant roadblock to transcribing modern Ivrit.

**Comment by JacobWeinbren** [comment]
@charlesLoder Using the Additional Feature, would something like this be what you are looking for? We would need to add syllable.previous to go along with syllable.next

```javascript
const heb = require("hebrew-transliteration");
const brillSimple = require("hebrew-transliteration/schemas").brillSimple;

let text = "גְּדֹולִים";
let transliterated = heb.transliterate(text, brillSimple, {
	ADDITIONAL_FEATURES: [
		{
			HEBREW: "(?<![\u{05B1}-\u{05BB}\u{05C7}].*)\u{05B0}",
			FEATURE: "syllable",
			TRANSLITERATION: function (syllable, _hebrew, schema) {
				// If the shva should be vocal
				if (
					(syllable.position === 0 &&
						["י", "ל", "מ", "נ", "ר"].includes(syllable.onset)) ||
					(syllable.position === 1 &&
						["א", "ה", "ע"].includes(syllable.onset)) ||
					(syllable.previous &&
						syllable.previous.vowel === "\u{05B0}")
				) {
					return syllable.text.replace(
						new RegExp("\u{05B0}", "u"),
						brillSimple.VOCAL_SHEVA
					);
				}
				// If none of the conditions are met, the shva is silent
				return syllable.text.replace(new RegExp("\u{05B0}", "u"), "");
			},
		},
	],
});

console.log(transliterated);
```

**Comment by charlesLoder** [comment]
@JacobWeinbren 

Here is a solution:

```js
const str = "גְּדֹולִים לְבָנִים תְּשׁוּקָה תְּאוּנָה";
console.log(
  heb.transliterate(str, {
    longVowels: false,
    ADDITIONAL_FEATURES: [
      {
        FEATURE: "syllable",
        HEBREW: "\u{05B0}",
        TRANSLITERATION: (syllable, _hebrew, schema) => {
          // if vowel is not a shewa then shewa is silent, so skip
          if (syllable.vowel !== "\u{05B0}") return syllable.text;

          // if syllable vowel is a shewa and contains one of the following, then the shewa is vocal
          if (["י", "ל", "מ", "נ", "ר"].includes(syllable.onset)) {
            return syllable.text;
          }

          // if the syllable vowel is a shewa and the next syllable contains a guttural, then the shewa is vocal
          const next = syllable?.next?.value.onset;
          if (next && ["א", "ה", "ע"].includes(next)) {
            return syllable.text;
          }

          // else the shewa is silent
          return syllable.text.replace("\u{05B0}", "");
        }
      }
    ]
  })
);
// gdôlîm lǝbānîm tšûqâ tǝʾûnâ
```

As for an initial vav, thought the rules above would indicate that it is silent, I'm pretty sure it should be vocal.

Somewhere else you asked about — הוֹלְכִים. In Modern Israeli, a shewa after a long vowel is usually silent (like in the phrase "[eykh omrim](https://youtu.be/PKQKH8moFe8?t=50)"). Theoretically, the `longVowels` option set to `false` should work, but there is a bug I need to fix

**Comment by JacobWeinbren** [comment]
@charlesLoder 

Thanks a lot!

One fix to your code

`const next = syllable?.next?.value?.onset;`

(if the syllable is the last one it checks first).

Could we write in an edge case if the word begins with ve (וְ) 'and'? It is one of the most common lexemes (I'm sure you knew this already, apologies). Something like:

```javascript
{
	FEATURE: "word",
	HEBREW: "^וְ",
	TRANSLITERATION: function (word, _hebrew, schema) {
		return word.text.replace("\u{05B0}", schema["VOCAL_SHEVA"]);
	},
},
```

Also, is there a way to transliterate using the additional features and use the brillSimple schema - can you use both at the same time? For some reason, using heb.transliterate(str, schema, {...}) isn't possible.

Also, Is there any way I can help you with fixing the longVowels option? 

Thanks again!

**Comment by charlesLoder** [comment]
The longVowel option is part of the havarotjs package. I still need to make the issue for it.

> (if the syllable is the last one it checks first).

Not sure I follow. 

Here's an updated solution:

```js
const str = "וְמֶלֶךְ יַלְדָּה גְּדֹולִים לְבָנִים תְּשׁוּקָה תְּאוּנָה";
console.log(
  heb.transliterate(str, {
    longVowels: false,
    ADDITIONAL_FEATURES: [
      {
        FEATURE: "syllable",
        HEBREW: /^\D{1,2}\u{05B0}/,
        TRANSLITERATION: (syllable, _hebrew, schema) => {
          // if vowel is not a shewa then shewa is silent, so skip
          if (syllable.vowel !== "\u{05B0}") {
            return syllable.text;
          }

          // if it is the first syallble and is conjunctive vav, then the shewa is vocal
          const isFirstSyllable = syllable.prev ? false : true;
          if (isFirstSyllable && syllable.text.includes("וְ")) {
            return syllable.text;
          }

          // if syllable vowel is a shewa and contains one of the following, then the shewa is vocal
          if (["י", "ל", "מ", "נ", "ר"].includes()) {
            return syllable.text;
          }

          // if the syllable vowel is a shewa and the next syllable contains a guttural, then the shewa is vocal
          const next = syllable?.next?.value.onset;
          if (next && ["א", "ה", "ע"].includes(next)) {
            return syllable.text;
          }

          // else the shewa is silent
          return syllable.text.replace("\u{05B0}", "");
        }
      }
    ]
  })
);
// wǝmelek yaldâ gdôlîm lbānîm tšûqâ tǝʾûnâ
```

Note the updated regex — `/^\D{1,2}\u{05B0}/`

You can fiddle around with it.

You can also extend a premade schema with destructuring

```js
heb.transliterate(str, {
    ...brillSimple,
    ADDITIONAL_FEATURES: [
    // all the stuff
  ]
});

**Comment by JacobWeinbren** [comment]
Thank you for this. Regarding the longvowel if you make it an issue, I will try my best to help. How much does it come up in Hebrew do you think?

```
const next = syllable?.next?.value.onset;
                                                                          ^
TypeError: Cannot read properties of undefined (reading 'onset')
    at TRANSLITERATION (/Users/jacobweinbren/Desktop/test/test.js:32:40)
    at sylRules (/Users/jacobweinbren/Desktop/test/node_modules/hebrew-transliteration/dist/rules.js:274:70)
    at /Users/jacobweinbren/Desktop/test/node_modules/hebrew-transliteration/dist/transliterate.js:83:50
    at Array.map (<anonymous>)
    at /Users/jacobweinbren/Desktop/test/node_modules/hebrew-transliteration/dist/transliterate.js:83:18
    at Array.map (<anonymous>)
    at Object.transliterate (/Users/jacobweinbren/Desktop/test/node_modules/hebrew-transliteration/dist/transliterate.js:78:10)
    at Object.<anonymous> (/Users/jacobweinbren/Desktop/test/test.js:7:6)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
```

This is the error I get without adding the question mark. I think it is an error with the last syllable (which does not have a next).

Without going on too much of a tangent from the original issue (which you have very kindly solved), some exceptions still do not work due to the third rule, such as:

מִשְׁפְּחֹת = mishpechot

To solve this, I implemented this...hopefully this is ok?

```javascript
{
  FEATURE: "word", // Apply rule at the word level
  HEBREW: /\u{05B0}/,  // Match Shva sign anywhere in word
  
  TRANSLITERATION: function (word, _hebrew, schema) {
    // Regular expression to match two consecutive Shvas with possible intervening diacritics
    const regex = /([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})/gu;

    // Replace each match with first and third group followed by a vocal Shva
    const replaced = word.text.replace(regex, `$1$3${schema["VOCAL_SHEVA"]}`);
    
    return replaced; // Return transliterated word
  },
},
```

**Comment by JacobWeinbren** [comment]
@charlesLoder We can use similar code to make the shva after the long vowel ((hireq, qamets, tsere, segol, qibbuts, and shuruq) silent.

```javascript
{
  FEATURE: "word", // Apply rule at word level
  HEBREW: /\u{05B0}/,  // Match Shva sign anywhere in word
  
  TRANSLITERATION: function (word, _hebrew, schema) {
    // Regular expression to match a Shva following a long vowel with possible intervening diacritics
    const regex = /([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*[\u{05B1}\u{05B3}\u{05B4}\u{05B5}\u{05B8}\u{05BB}][\u{0591}-\u{05C7}]*)(\u{05B0})/gu;
    
    // Replace each match with the first group, effectively removing the Shva
    const replaced = word.text.replace(regex, `$1`);
    
    return replaced; // Return transliterated word
  },
},
```

**Comment by JacobWeinbren** [comment]
@charlesLoder Here is the full code to handle modern Ivrit.

```javascript
const heb = require("hebrew-transliteration");
const brillSimple = require("hebrew-transliteration/schemas").brillSimple;

const schema = {
	...brillSimple,
	longVowels: false,
	ADDITIONAL_FEATURES: [
		{
			FEATURE: "word", // Apply rule at the word level
			HEBREW: /\u{05B0}/, // Match Shva sign anywhere in word

			TRANSLITERATION: function (word, _hebrew, schema) {
				// Regular expression to match two consecutive Shvas with possible intervening diacritics
				const regex =
					/([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})/gu;

				// Replace each match with first and third group followed by a vocal Shva
				const replaced = word.text.replace(
					regex,
					`$1$3${schema["VOCAL_SHEVA"]}`
				);

				return replaced; // Return transliterated word
			},
		},
		{
			FEATURE: "syllable", // Work on the syllable level
			HEBREW: /\u{05B0}/, // Match Shva in a syllable
			TRANSLITERATION: function (syllable, _hebrew, schema) {
				// If Shva follows a long vowel, make it silent
				if (
					syllable.prev &&
					[
						"\u{05B4}",
						"\u{05B8}",
						"\u{05B5}",
						"\u{05B9}",
						"\u{05BB}",
					].includes(syllable.prev.vowel) &&
					syllable.vowel === "\u{05B0}"
				) {
					return syllable.text.replace(/\u{05B0}/u, "");
				}
				// Make second of consecutive Shvas vocal
				const replaced = syllable.text.replace(
					/([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})/gu,
					`$1$3${schema["VOCAL_SHEVA"]}`
				);
				return replaced;
			},
		},
		{
			FEATURE: "syllable",
			HEBREW: /^\D{1,2}\u{05B0}/,
			TRANSLITERATION: (syllable, _hebrew, schema) => {
				// if vowel is not a shewa then shewa is silent, so skip
				if (syllable.vowel !== "\u{05B0}") {
					return syllable.text;
				}

				// if it is the first syallble and is conjunctive vav, then the shewa is vocal
				const isFirstSyllable = syllable.prev ? false : true;
				if (isFirstSyllable && syllable.text.includes("וְ")) {
					return syllable.text;
				}

				// if syllable vowel is a shewa and contains one of the following, then the shewa is vocal
				if (
					["י", "ל", "מ", "נ", "ר"].includes(syllable.text.charAt(0))
				) {
					return syllable.text;
				}

				// if the syllable vowel is a shewa and the next syllable contains a guttural, then the shewa is vocal
				const next = syllable?.next?.value?.onset;
				if (next && ["א", "ה", "ע"].includes(next)) {
					return syllable.text;
				}

				// else the shewa is silent
				return syllable.text.replace("\u{05B0}", "");
			},
		},
	],
};

console.log(heb.transliterate("בְּרוּכָה הַבָּאָה", schema));
console.log(heb.transliterate("הוֹלְכִים", schema));
console.log(heb.transliterate("יַלְדָּה", schema));
console.log(heb.transliterate("מִשְׁפְּחֹת", schema));
```

Produces
```
brukha habba’a
holkhim
ylada
mishpᵉḥot
```

Switching to the regex you suggested makes it work, but produces a new error

```
brukha habba’a
holᵉkhim
yalda
mishpᵉḥot
```

**Comment by JacobWeinbren** [comment]
@charlesLoder I don't understand why this causes the letters to switch

```
{
			FEATURE: "syllable",
			// Regular expression to match Shva in a word
			HEBREW: /\D{1,2}\u{05B0}/,
			// Replace consecutive Shvas with a vocal Shva
			TRANSLITERATION: (syllable, _, schema) => {
				return syllable.text;
			},
		},
```

It makes it hard to fix the מַה שְּׁלוֹמֵךְ problem

**Comment by charlesLoder** [comment]
> I don't understand why this causes the letters to switch in yalda

Normally, that issue arises from this block

https://github.com/charlesLoder/hebrew-transliteration/blob/6f97bf7b42d715cc60da6aa600747d592fe652fa/src/rules.ts#L350-L355

It's just a poor design choice I made that needs to be refactored.


> This is the error I get without adding the question mark. I think it is an error with the last syllable (which does not have a next).

You'll want to have the question marks for [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining); they're useful to see if the value exists or not.

**Comment by JacobWeinbren** [comment]
@charlesLoder I can't find any obvious solution other than reversing clusters, but this causes even more problems.

With the final return changed to `return syllable.text.replace(/\u{05B0}/u, "");` I am getting this

brukha habba’a // correct
holkhim // correct
ylada // should be: yalda
mishpᵉḥot // correct
vᵉ’ani // correct
mah shlomkhe // should be: mah shlomekh

Thanks for posting the longVowels issue, I will take a look.

**Comment by JacobWeinbren** [comment]
@charlesLoder Managed to fix the word ordering bug and potentially the long vowel issue you raised - but אַנְגְּלִית produces issues. Not sure what I can do about these exceptions, or is there a rule I am missing?

**Comment by JacobWeinbren** [comment]
https://docs.google.com/spreadsheets/d/1abxso4ZnnZ_fPQv4aWf5vwmvLYODcofahH_MncB8-nE/edit#gid=0

I didn't want to make this public - but I've tested the new transliteration
for Shva in this spreadsheet in the 'New Translit' Column.

Thanks,
Jacob

**Comment by charlesLoder** [comment]
@JacobWeinbren 

What's your schema look like now?

**Comment by JacobWeinbren** [comment]
@charlesLoder It looks like this - thanks a lot!

```javascript
const heb = require("hebrew-transliteration");
const brillSimple = require("hebrew-transliteration/schemas").brillSimple;

// Arrays of characters for different conditions
const longVowels = ["\u{05B4}", "\u{05B8}", "\u{05B5}", "\u{05B9}", "\u{05BB}"];
const gutturals = ["א", "ה", "ע"];
const vocalChars = ["י", "ל", "מ", "נ", "ר"];

const schema = {
	...brillSimple,
	longVowels: false,
	ADDITIONAL_FEATURES: [
		{
			FEATURE: "word",
			// Regular expression to match Shva in a word
			HEBREW: /\D{1,2}\u{05B0}/,
			// Replace consecutive Shvas with a vocal Shva
			TRANSLITERATION: (word, _, schema) =>
				word.text.replace(
					/([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})/gu,
					`$1$3${schema["VOCAL_SHEVA"]}`
				),
		},
		{
			FEATURE: "syllable",
			// Regular expression to match Shva at the start of a syllable
			HEBREW: /\D{1,2}\u{05B0}/,
			// Handle rules of Shva in a syllable
			TRANSLITERATION: (syllable, _, schema) => {
				const isFirstSyllable = !syllable.prev;
				const nextOnset = syllable?.next?.value?.onset;

				if (
					// If Shva follows a long vowel, make it silent
					syllable.vowel === "\u{05B0}" &&
					syllable.prev &&
					longVowels.includes(syllable.prev.vowel)
				) {
					return syllable.text.replace(/\u{05B0}/u, "");
				}

				if (
					// If Shva is in the first syllable and is a conjunctive vav, make it vocal
					(isFirstSyllable && syllable.text.includes("וְ")) ||
					// If Shva follows one of the characters in vocalChars, make it vocal
					vocalChars.includes(syllable.text.charAt(0)) ||
					// If the next syllable contains a guttural, make Shva vocal
					(nextOnset && gutturals.includes(nextOnset))
				) {
					return syllable.text;
				}

				return syllable.text.replace(/\u{05B0}/u, "");
			},
		},
	],
};
```

**Comment by JacobWeinbren** [comment]
@charlesLoder One of the issues with long vowels is the other kinds of long vowels that aren't just below letters. הוֹלְכִים has a vav with a dot on top. In havarotjs, syllable.vowel says the vowel is null, and the letter is a vav.

**Comment by charlesLoder** [comment]
Using the schema [here](https://github.com/charlesLoder/hebrew-transliteration/issues/70#issuecomment-1575308885), you can adjust the regex a little more:

```diff
- HEBREW: /\D{1,2}\u{05B0}/,
+ HEBREW: /^\D{1}[\u{05C1}|\u{05C2}]?\D{1}\u{05B0}/,
```
These regexes can get a little complicated.


> In havarotjs, syllable.vowel says the vowel is null, and the letter is a vav. Which is why it isn't being picked up.

OK, I'll look into that a little more.

---

At some point, I need to sit down with both of these projects and really consider some good changes.

**Comment by JacobWeinbren** [comment]
@charlesLoder Do you know whether your long vowel system can detect whether a letter with a dot (i.e the abbreviated) version contains a long vowel. e.g. חֹ?

**Comment by JacobWeinbren** [comment]
@charlesLoder Also, thanks a lot for continuing to help!!

**Comment by JacobWeinbren** [comment]
@charlesLoder Oh - I see what you are asking. Updated your post.

**Comment by JacobWeinbren** [comment]
@charlesLoder btw - unrelated - this list might help you http://bhebrew.biblicalhumanities.org/viewtopic.php?f=16&t=22441&sid=31c181446205ac7bc1bb93ddf59c0b51

**Comment by JacobWeinbren** [comment]
@charlesLoder Not to go full circle. I removed the letter-switching change I made, and added detection for holam male. It works for holkhim. But yalda is still acting up.

**Comment by JacobWeinbren** [comment]
@charlesLoder Finally can get some sleep.

Ok so the pull request I have tested and it works. The issue with the long vowels? You can see it being tested here.` /^\D{1}[\u{05C1}|\u{05C2}]?\D{1}\u{05B0}/` seems to breaks things but if you can show me how to make it work properly - I'm open ears.

```javascript
const heb = require("hebrew-transliteration");
const brillSimple = require("hebrew-transliteration/schemas").brillSimple;

// Arrays of characters for different conditions
const gutturals = ["א", "ה", "ע"];
const vocalChars = ["י", "ל", "מ", "נ", "ר"];

const schema = {
	...brillSimple,
	longVowels: false,
	ADDITIONAL_FEATURES: [
		{
			FEATURE: "word",
			// Regular expression to match Shva in a word
			HEBREW: /\D{1,2}\u{05B0}/,
			// Replace consecutive Shvas with a vocal Shva
			TRANSLITERATION: (word, _, schema) =>
				word.text.replace(
					/([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})([\u{05D0}-\u{05EA}][\u{0591}-\u{05C7}]*)(\u{05B0})/gu,
					`$1$3${schema["VOCAL_SHEVA"]}`
				),
		},
		{
			FEATURE: "syllable",
			// Regular expression to match Shva at the start of a syllable
			HEBREW: /\D{1,2}\u{05B0}/,
			// Handle rules of Shva in a syllable
			TRANSLITERATION: (syllable, _, schema) => {
				const isFirstSyllable = !syllable.prev;
				const nextOnset = syllable?.next?.value?.onset;

				if (
					// If Shva follows a long vowel, make it silent
					syllable.prev &&
					/[\u{05B5}\u{05B8}\u{05B9}\u{05BA}\u05B9]/u.test(
						syllable.prev.text
					)
				) {
					return syllable.text.replace(/\u{05B0}/u, "");
				}

				if (
					// If Shva is in the first syllable and is a conjunctive vav, make it vocal
					(isFirstSyllable && syllable.text.includes("וְ")) ||
					// If Shva follows one of the characters in vocalChars, make it vocal
					vocalChars.includes(syllable.text.charAt(0)) ||
					// If the next syllable contains a guttural, make Shva vocal
					(nextOnset && gutturals.includes(nextOnset))
				) {
					return syllable.text;
				}

				return syllable.text.replace(/\u{05B0}/u, "");
			},
		},
	],
};

console.log(heb.transliterate("בְּרוּכָה הַבָּאָה", schema));
console.log(heb.transliterate("הוֹלְכִים", schema));
console.log(heb.transliterate("יַלְדָּה", schema));
console.log(heb.transliterate("מִשְׁפְּחֹת", schema));
console.log(heb.transliterate("וְאָנִי", schema));
console.log(heb.transliterate("מַה שְּׁלוֹמֵךְ", schema));
*/

```
