### ISSUE TITLE
Add Journal of Semitic Studies schema

### ISSUE THREAD

**Issue by charlesLoder** [charlesLoder/hebrew-transliteration#73]
See @camilstaps original issue [here](https://github.com/charlesLoder/hebrewTransliteration/issues/71)

> I don't think it's possible to recognize short/long vowels(?) to distinguish e.g. i and ī, so I used ī for hireq-yod and i for plain hireq, which may require some manual fixes from the user (what would be helpful for this is a separate field for hireq+meteg and qibbuts+meteg).

Could you provide examples? I think the `ADDITIONAL_FEATURES` may be able to account for that.
<br>
<br>

> The style guide also prescribes that qamets before hatef qamets be transliterated as long qamets: בַּֽצָּהֳרָֽיִם should be baṣṣå̄hå̆rå̄yim, not baṣṣåhå̆rå̄yim. I am not sure if this can be specified in the current system.

Interesting, so they say the qamets under the tsade should be a qamets qatan, but they maintain a distinction between qamets qatan and qamets gadol in transliteration. The stlyesheet says:

> This transcription of the quality of the vowels corresponds to the Tiberian reading tradition of Biblical Hebrew,
with the exception of the shewa. The distribution of vocalic and silent shewa, however, follows the Tiberian
tradition. 

Given that Khan is the editor, I would _assume_ that means there is no distinction between qamets qatan and qamets gadol. Maybe I'll have to pry into this one.

<br>
<br>

> Tsere-he is not recognized correctly, I'm not sure why: וְהִנֵּ֥ה should be wǝhinnē, not wǝhinnɛ.

I'll research that.

<br>
<br>

Let me know what you think of the two questions above.

---

Initial JSON

```json
{
  "VOCAL_SHEVA": "ǝ",
  "HATAF_SEGOL": "ɛ̆",
  "HATAF_PATAH": "ă",
  "HATAF_QAMATS": "å̆",
  "HIRIQ": "i",
  "TSERE": "ē",
  "SEGOL": "ɛ",
  "PATAH": "a",
  "QAMATS": "å̄",
  "HOLAM": "ō",
  "QUBUTS": "u",
  "DAGESH": "",
  "DAGESH_CHAZAQ": true,
  "MAQAF": " ",
  "PASEQ": "",
  "SOF_PASUQ": "",
  "QAMATS_QATAN": "å",
  "FURTIVE_PATAH": "a",
  "HIRIQ_YOD": "ī",
  "TSERE_YOD": "ē",
  "SEGOL_YOD": "ɛ",
  "SHUREQ": "ū",
  "HOLAM_VAV": "ō",
  "QAMATS_HE": "å̄",
  "SEGOL_HE": "ɛ",
  "TSERE_HE": "ē",
  "MS_SUFX": "å̄yw",
  "ALEF": "ʾ",
  "BET_DAGESH": "b",
  "BET": "ḇ",
  "GIMEL": "ḡ",
  "GIMEL_DAGESH": "g",
  "DALET": "ḏ",
  "DALET_DAGESH": "d",
  "HE": "h",
  "VAV": "w",
  "ZAYIN": "z",
  "HET": "ḥ",
  "TET": "ṭ",
  "YOD": "y",
  "FINAL_KAF": "ḵ",
  "KAF": "ḵ",
  "KAF_DAGESH": "k",
  "LAMED": "l",
  "FINAL_MEM": "m",
  "MEM": "m",
  "FINAL_NUN": "n",
  "NUN": "n",
  "SAMEKH": "s",
  "AYIN": "ʿ",
  "FINAL_PE": "p̄",
  "PE": "p̄",
  "PE_DAGESH": "p",
  "FINAL_TSADI": "ṣ",
  "TSADI": "ṣ",
  "QOF": "q",
  "RESH": "r",
  "SHIN": "š",
  "SIN": "ś",
  "TAV": "ṯ",
  "TAV_DAGESH": "t",
  "DIVINE_NAME": "yhwh",
  "SYLLABLE_SEPARATOR": "",
  "ADDITIONAL_FEATURES": [],
  "STRESS_MARKER": {
    "location": "",
    "mark": ""
  },
  "longVowels": true,
  "qametsQatan": true,
  "sqnmlvy": true,
  "wawShureq": true,
  "article": true
}
```

**Comment by charlesLoder** [comment]
Acc. to the senior editor: 

> In the Tiberian reading tradition there is no distinction in the quality of qameṣ gadol and qameṣ qaṭan. However, there is a difference in the quantity, which is indicated in the different diacritics in our transcription system.

In Khan's _Tiberian Pronunciation_ v1, the difference between _qamets qatan_ and _qamets gadol_ (though he never says those terms) is length.

**Qatan**
See: קָדְשֵׁי [qɔðˈʃeː]
and: כָּל־ [kʰɔl]
with short vowels as indicated by no ː mark.

**Gadol**
The "typical" qamets usuall has a ː mark.
See: יָמִים [jɔːˈmiːim]

---

As for the schema, I think an `ADDITIONAL_FEATURE` may work. Something like this untested code:

```js
{
  ADDITIONAL_FEATURES: [
    {
      FEATURE: "syllable",
      // if the syllable contains a qamets qatan character
      HEBREW: /\u{05C7}/,
      TRANSLITERATION: (syllable) => {
        const next = syllable?.next?.value?.text;
        // if the next syllable includes a hateph qamets, then replace the qamets qatan with a regular qamets 
        if(next && next.includes("\u05B3')) {
          return syllable.text.replace("\u{05C7}", "\u{05B8}")
        }
        return syllable.text
      }
    }
  ]
}
```

**Comment by camilstaps** [comment]
That's great! I didn't realize an `ADDITIONAL_FEATURE` could contain code, then something similar should definitely work to recognize hireq/qibbuts + meteg as well.

If you want, I can have a go, but it may take a while, I have a lot on my plate at the moment. Totally understandable if that's also the case for you of course!

**Comment by charlesLoder** [comment]
@camilstaps have at it! I'm totally swamped too :) 

There's a folder for [schema tests](https://github.com/charlesLoder/hebrew-transliteration/tree/main/test/schemas), that would be my only ask. You can just duplicate sblSimple, and add test for these special cases.
