### ISSUE TITLE
Stress, gemination, and multicharacter transliteration

### ISSUE THREAD

**Issue by ben-hull** [charlesLoder/hebrew-transliteration#98]
I have "STRESS_MARKER": {"location": "before-syllable"}, and "DAGESH_CHAZAQ": true. I also have some consonants transliterated with multiple characters, eg. "TET": "tˤ".
In this case, it will output <hammitˈˤtˤah>, with the stress mark in the wrong place. It should be <hammitˤˈtˤah>.

[hebrew ipa spirantized.json](https://github.com/user-attachments/files/18087401/hebrew.ipa.spirantized.json)

**Comment by charlesLoder** [comment]
@ben-hull 

Digraphs are a little tricky. The `tiberian` schema has some helpful examples for digraphs like this:

https://github.com/charlesLoder/hebrew-transliteration/blob/70b4e9cb82ab505954bd9694360d31cc7a67a5e6/src/schemas/tiberian.ts#L119-L136


This worked for me with 

```js
{
  FEATURE: "cluster",
  HEBREW: /טּ(?!\u{05b0})/u,
  TRANSLITERATION: (cluster, _, schema) => { 
    if (!cluster.prev || cluster.prev.value?.isNotHebrew) { return cluster.text; } 
    const prevCoda = cluster.syllable?.prev?.value?.codaWithGemination; 
    if (!prevCoda?.includes('ט')) { return cluster.text; } ;
    const noPharyngealization = schema['TET']?.replace('ˤ', '') ?? ''; 
    return cluster.text.replace('ט', `${noPharyngealization + schema['TET']}`);
}
```

Though note that the `ˤ` character I used ([U+02E4](https://www.compart.com/en/unicode/U+02E4)) is different than the character you used `ˁ` ([U+02C1](https://www.compart.com/en/unicode/U+02C1)). I have no idea if one is more "right" than the other

Let me know if that works!

The

**Comment by ben-hull** [comment]
Thanks, I got it to work! 
BTW I really appreciate all the work that went into this, there's a small intersection of people who can do both the coding and the phonology necessary to create something this sophisticated! 
And wow, I never noticed there were two different codepoints for `ˤ`, I just typed it using my (now deprecated) IPA keyboard.
